import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const alata = Alata({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-alata",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Junaid Jamshed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
